---
title: "Carte des RPU produits par territoire de santé"
author: "JcB - RESURAL"
date: "08/01/2016"
output:
  pdf_document:
    keep_tex: yes
  html_document:
    keep_md: yes
  word_document: default
---

Les RPU sont représentés par des cercles dont la superficie est proportionnelle au nombre de RPU produits par chacun des douze territoires de proximité.


```{r, echo=FALSE, message=FALSE}
anc <- "2015"
library(sp)
library(knitr)
library(Rpu2)
par(mar = c(0,0,2,0))

# en mode console retirer ../../
load("../../../../Stat Resural/RPU_Doc/RPU_Carto-Pop-Alsace/Cartographie/Cartofile/als_ts.Rda") #ctss
load("../../../../Stat Resural/RPU_Doc/RPU_Carto-Pop-Alsace/Cartographie/Cartofile/tsvilles.Rda") # tsvilles

```
```{r, echo=FALSE}
# calcul du nombre de RPU par TP en 2014 et 2015. La création des zones varie selon l'année. Par exemple HUS existe en 2014 mais remplacé par NHC et HTP en 2015. Pour 2016, Mul sera remplacé par Hsr et Emr.
if(anc == 2014){
  load("/home/jcb/Documents/Resural/Stat Resural/DATA/RPU_2014/rpu2014d0112_c2.Rda")
  dx <- d14
  t <- tapply(as.Date(dx$ENTREE), dx$FINESS, length)
  rpu <- c(t['Wis'], t['Sel'], t['Hag'], t['Sav'], NA, t['Hus']+t['Ane']+t['Odi']+t['Dts'], t['3Fr'], NA, t['Alk'], t['Col'],t['Mul']+t['Dia']+t['Ros'], t['Geb'])
} else if(anc == 2015){
  load("/home/jcb/Documents/Resural/Stat Resural/RPU_2014/rpu2015d0112.Rda")
  dx <- d15
  t <- tapply(as.Date(dx$ENTREE), dx$FINESS, length)
  rpu <- c(t['Wis'], t['Sel'], t['Hag'], t['Sav'], NA, t['HTP']+t['NHC']+t['Ane']+t['Odi']+t['Dts'], t['3Fr'], NA, t['Alk'], t['Col'], t['Mul']+t['Dia']+t['Ros']+t['Emr']+t['Hsr'], t['Geb'])

}

# ajout de la colonne rpu à tsvilles
tsvilles$rpu <- rpu

```

```{r carte_prod, fig.height=8, echo=FALSE}
# carte générale
plot(ctss, main = paste("Nombre de RPU produits par zone de proximité en", anc), col = "palegreen")

# on tace des points proportionnels
bg <- "cornflowerblue"
cex <- 0.05
points(tsvilles[,2]*100,tsvilles[,3]*100, pch=21, col="white", bg = bg, cex = cex * sqrt(tsvilles$rpu / pi))
text(tsvilles[,2]*100,tsvilles[,3]*100,tsvilles[,1],cex=0.7,pos=4)
rpu_legend <- c(10000, 30000, 60000, 100000)
legend("topleft", legend = rpu_legend, pch = 21, col = "white", pt.bg = bg, bty = "n", pt.cex = cex * sqrt(rpu_legend / pi), title = "Nombre de RPU")

```

La surface des cercles est proportionnelle au nombre de RPU. Il manque des informations sur deux territoires: Schirmeck et Thann. En 2014, le nombre de RPU de la zone Strasbourg est fortement sous estimé.

```{r, echo=FALSE, results='asis'}
# tableau de chiffres
library(xtable)
tab <- tsvilles[, c(1, 4)] # on garde les colonnes 1 et 4
tab <- tab[order(tab[,1]),] # tri alphabétique

# ajout d'une ligne TOTAL
TOTAL <- sum(tab[, "rpu"], na.rm = TRUE) # total des RPU
tab[, 1] <- as.character(tab[, 1]) # 

tab <- rbind(tab, c("TOTAL", TOTAL))
tab[, 2] <- as.numeric(tab[, 2]) #
colnames(tab) <- c("Zone de proximité", "Nombre de RPU")

kable(tab, caption = paste0("RPU produits en ", anc, " par zone de proximité"), format.args = list(big.mark = " ", decimal.mark = ","))

# sauvegarde de la table tab pour usage ultérieur:

write.csv(tab, file = paste0("tab", anc, ".csv"), row.names = FALSE)

```

```
Source: RPU_2014/Analyse/Carte_RPU_TP
```