---
title: "Activité 2013-2014"
author: "jcb"
date: "24 avril 2015"
output:
  html_document:
    keep_md: yes
---

Problème: comparer l'activité des SU pendant la période de tension au cours des années 2013 à 2015.

ref: http://stackoverflow.com/questions/4843969/plotting-time-series-with-date-labels-on-x-axis

pour les graduations de l'axe des x: http://earlh.com/blog/2009/07/07/plotting-with-custom-x-axis-labels-in-r-part-5-in-a-series/

```{r}
library(lubridate)
library(xts)
source("../Temps_passage/passage.R")
source("activite_tension.R") # graphique

# récupérer les 3 années
load("~/Documents/Stat Resural/RPU_2014/rpu2014d0112_c2.Rda")
load("~/Documents/Stat Resural/RPU_2014/rpu2015d0112_provisoire.Rda")
load("~/Documents/Stat Resural/RPU_2013/rpu2013d0112.Rda")
dx <- rbind(d1, d14, d15)

# on se limite aux 4 premier mois de l'année (pas de données pour décembre 2012)
dxt1 <- dx[as.Date(dx$ENTREE) >= "2013-01-01" & as.Date(dx$ENTREE) < "2013-04-15",]
dxt2 <- dx[as.Date(dx$ENTREE) >= "2014-01-01" & as.Date(dx$ENTREE) < "2014-04-15",]
dxt3 <- dx[as.Date(dx$ENTREE) >= "2015-01-01" & as.Date(dx$ENTREE) < "2015-04-15",]

# on forme un grand dataframe
# dt = RPU des 4 premiers mois des années 2013 à 2015
dt <- rbind(dxt1,dxt2,dxt3)

head(dt)

# pour chaque jour de la période (jours transformés en n° du jour de l'année), on calcule le nombre de RPU. On obtient une matrice de 3 lignes (1 par année) et 98 jours.
rpu.jour <- tapply(as.Date(dt$ENTREE), list(yday(as.Date(dt$ENTREE)), year(as.Date(dt$ENTREE))), length)

# La matrice est transformée en dataframe
rpu.jour <- data.frame(rpu.jour)

# auquel on ajoute une colonne de dates.On choisit arbitrairement 2015 pour les dates
x <- seq(as.Date("2015-01-01"), as.Date("2015-04-14"), 1)
rpu.jour$date <- x

head(rpu.jour)

# graphique
graphe.activite(rpu.jour)

```

Même chose pour les 75 ans et plus:
```{r rpu75}
dx75 <- dx[dx$AGE > 74,]
rpu.jour.75 <- create.dxt(dx75)
graphe.activite(rpu.jour.75, "75 ans et plus")
```

Proportion des 75 ans et plus au sein de l'ensemble des passages. On calcule la proportion rpu.jour.75 sur rpu.jour.
```{r prop.75}
prop <- rpu.jour.75[1:3] * 100 / rpu.jour[1:3]
prop$date <- rpu.jour$date
graphe.activite2(prop, "% 75 ans et plus")

```

